services:
  loadbalancer:
    image: nginx:1.27.4-alpine3.21
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - app
    volumes:
      - ./configs/snippets:/etc/nginx/snippets
      - ./configs/loadbalancer.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/loadbalancer/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./certs/loadbalancer/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./certs/loadbalancer/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
  
  app:
    image: nginx:1.27.4-alpine3.21
    volumes:
      - ./configs/snippets:/etc/nginx/snippets
      - ./configs/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/app/dhparam.pem:/etc/nginx/dhparam.pem:ro
      - ./certs/app/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./certs/app/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
      - ./html/index.html:/var/www/html/index.html:ro
